<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <DocumentationFile>ConstTypeArgs.Chars.xml</DocumentationFile>
    <PackageIcon>Char.png</PackageIcon>
    <PackageReadmeFile>README.MD</PackageReadmeFile>
    <Company>Entry Point Software</Company>
    <Authors>Zachary Layne</Authors>
    <Title>Const Type Arguments - Chars</Title>
    <Copyright>Copyright (c) 2024 Zachary Layne</Copyright>
    <RepositoryUrl>https://github.com/zacharylayne/ConstTypeArgs</RepositoryUrl>
    <IncludeSource>true</IncludeSource>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageTags>constants; const-type-args; generics; static-abstract-interface-members; char</PackageTags>
    <PackageReleaseNotes>Initial release.</PackageReleaseNotes>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <DocumentationFile>ConstTypeArgs.Chars.xml</DocumentationFile>
    <Description>ConstTypeArgs.Chars extends the ConstTypeArgs.Core library by enabling you to “pass” char values as generic type parameters, accessible from within static contexts. This lets you customize types in a compile-time–like fashion, effectively mimicking C++ template specialization.

This lightweight solution provides type-level char values for cleaner, more efficient, and more expressive code, making it ideal for:

- Static Configuration: Define behavior without relying on runtime parameters.
- Type Initializer Injection: Pass values directly to static constructors.
- Flexible Validation: Validate const type arguments in static constructors, field initializers, module initializers, via static analysis, etc.
- Constructors: Eliminate unnecessary instance-level initialization.
- And more.

The package provides const type arguments for all ASCII &amp; extended ASCII characters, as well as support for char arrays and domain-specific types.

Example:

using ConstTypeArgs.Chars;

// Const type arguments:
public readonly struct Comma : K_Byte&lt;Comma&gt;
{ public static char Value =&gt; ','; }

public readonly struct Semicolon : K_Byte&lt;Semicolon&gt;
{ public static char Value =&gt; ';'; }

public readonly struct Slash : K_Byte&lt;Slash&gt;
{ public static char Value =&gt;  (char)47; }

public readonly struct VerticalBar : K_Byte&lt;VerticalBar&gt;
{ public static char Value =&gt; '|'; }

public abstract class DefaultSeparator : Char&lt;Semicolon&gt; { }

// Usage:
public static class Foo&lt;TChar&gt;
    where TChar: K_Char
{
    private static readonly char Separator = TChar.Value;

    public static void Output(string[] items)
    {
        foreach (var item in items)
            Console.Write($"{item}{Separator}");
    }
}

// Elsewhere:
var helloWorld = new string[] { "Hello", "World!" };

Foo&lt;Comma&gt;.Output(helloWorld);                // Output: Hello,World!
Foo&lt;Slash&gt;.Output(helloWorld);                    // Output: Hello/World!
Foo&lt;VerticalBar&gt;.Output(helloWorld);            // Output: Hello|World!
Foo&lt;DefaultSeparator&gt;.Output(helloWorld); // Output: Hello;World!
</Description>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageProjectUrl>https://github.com/zacharylayne/ConstTypeArgs</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
    <IsTrimmable>True</IsTrimmable>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Deterministic>true</Deterministic>
    <IsTrimmable>True</IsTrimmable>
    <DebugType>portable</DebugType>
    <IncludeSource>true</IncludeSource>
    <EnableSourceLink>true</EnableSourceLink>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\Icons\Char.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ConstTypeArgs.Core" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.MD">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>
