<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Company>Entry Point Software</Company>
    <Authors>Zachary Layne</Authors>
    <Title>Const Type Arguments - Booleans</Title>
    <Description>ConstTypeArgs.Bools extends the ConstTypeArgs.Core library by enabling you to “pass” boolean values as generic type parameters, accessible from within static contexts. This lets you customize types in a compile-time–like fashion, effectively mimicking C++ template specialization.

This lightweight solution provides type-level boolean values for cleaner, more efficient, and more expressive code, making it ideal for:

- Static Configuration: Define behavior without relying on runtime parameters.
- Type Initializer Injection: Pass values directly to static constructors.
- Flexible Validation: Validate const type arguments in static constructors, field initializers, module initializers, via static analysis, etc.
- Constructors: Eliminate unnecessary instance-level initialization.
- And more.

The package provides const type arguments for true, false, and the default boolean value (false), plus support for boolean arrays and domain-specific boolean types.

Example:

using ConstTypeArgs.Bools;

public class Foo&lt;TToConsole&gt;
    where TToConsole : K_Bool
{
    static Foo()
    {        
        if (TToConsole.Value)
            Console.WriteLine("Hello, world!");
    }
}

// Usage:
var foo = new Foo&lt;True&gt;();   // Outputs: Hello, world!
foo = new Foo&lt;False&gt;();       // No output.
</Description>
    <Copyright>Copyright (c) 2024 Zachary Layne</Copyright>
    <PackageReadmeFile>README.MD</PackageReadmeFile>
    <PackageIcon>Bool.png</PackageIcon>
    <PackageTags>constants; const-type-args; generics; static-abstract-interface-members; bools</PackageTags>
    <PackageReleaseNotes>Initial release.</PackageReleaseNotes>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <DocumentationFile>ConstTypeArgs.Bools.xml</DocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <RepositoryUrl>https://github.com/zacharylayne/ConstTypeArgs</RepositoryUrl>
    <IncludeSource>true</IncludeSource>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <FileVersion>1.0.0.0</FileVersion>
    <PackageProjectUrl>https://github.com/zacharylayne/ConstTypeArgs</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
    <IsTrimmable>True</IsTrimmable>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Deterministic>true</Deterministic>
    <IsTrimmable>True</IsTrimmable>
    <DebugType>portable</DebugType>
    <IncludeSource>true</IncludeSource>
    <EnableSourceLink>true</EnableSourceLink>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ConstTypeArgs.Core" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\Icons\Bool.png" Link="Bool.png">
      <Pack>True</Pack>
      <PackagePath>/</PackagePath>
    </None>
    <None Include="README.MD">
      <Pack>True</Pack>
      <PackagePath>/</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>/</PackagePath>
    </None>
  </ItemGroup>

  </Project>
