<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <DocumentationFile>ConstTypeArgs.Decimals.xml</DocumentationFile>
    <PackageIcon>Decimal.png</PackageIcon>
    <PackageReadmeFile>README.MD</PackageReadmeFile>
    <Company>Entry Point Software</Company>
    <Authors>Zachary Layne</Authors>
    <Title>Const Type Arguments - Decimals</Title>
    <Copyright>Copyright (c) 2024 Zachary Layne</Copyright>
    <RepositoryUrl>https://github.com/zacharylayne/ConstTypeArgs</RepositoryUrl>
    <IncludeSource>true</IncludeSource>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageTags>constants; const-type-args; generics; static-abstract-interface-members; decimal</PackageTags>
    <PackageReleaseNotes>Initial release.</PackageReleaseNotes>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <DocumentationFile>ConstTypeArgs.Decimals.xml</DocumentationFile>
    <Description>ConstTypeArgs.Decimals extends the ConstTypeArgs.Core library by enabling you to “pass” decimal values as generic type parameters, accessible from within static contexts. This lets you customize types in a compile-time–like fashion, effectively mimicking C++ template specialization.

This lightweight solution provides type-level decimal values for cleaner, more efficient, and more expressive code, making it ideal for:

- Static Configuration: Define behavior without relying on runtime parameters.
- Type Initializer Injection: Pass values directly to static constructors.
Flexible Validation: Validate const type arguments in static constructors, field initializers, module initializers, via static analysis, etc.
- Constructors: Eliminate unnecessary instance-level initialization.
- And more.

The package provides const type arguments for  Default, MinValue, MaxValue, E, Pi, Phi, Tau, _0, _1, and Neg_1, and provides support for decimal arrays and domain-specific types.

Example:

using ConstTypeArgs.Decimals;

// Const type arguments:
public readonly struct _1_2345 : K_Decimal&lt;_1_2345&gt;
{ public static decimal Value = 1.2345; }

public readonly struct _6_789 : K_Decimal&lt;_6_789&gt;
{ public static decimal Value = 6.789; }

public abstract class DefaultValue : Decimal&lt;_1_2345&gt; { }

// Usage:
public static class Foo&lt;TDecimal&gt;
    where TDecimal : K_Decimal
{
    private static readonly decimal Value = TDecimal.Value;
}

// Elsewhere:
Console.WriteLine($"Foo's value if default: {Foo&lt;DefaultValue&gt;.");
Console.WriteLine($"Foo's non-default value: {Foo&lt;_6_789&gt;.Value}.");</Description>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageProjectUrl>https://github.com/zacharylayne/ConstTypeArgs</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
    <IsTrimmable>True</IsTrimmable>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Deterministic>true</Deterministic>
    <IsTrimmable>True</IsTrimmable>
    <DebugType>portable</DebugType>
    <IncludeSource>true</IncludeSource>
    <EnableSourceLink>true</EnableSourceLink>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\Icons\Decimal.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ConstTypeArgs.Core" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.MD">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>