#pragma warning disable format
namespace ConstTypeArgs.UnitsOfMeasure;

/// <summary>
/// The <see cref="IUnitInfo{TSelf}"/> interface adds unit information
/// to a const type argument.
/// </summary>
/// <typeparam name="TSelf">
/// The type itself.
/// </typeparam>
/// <seealso cref="UnitOfMeasure"/>
public interface IUnitInfo<TSelf>
    where TSelf : IUnitInfo<TSelf>
{
    /// <summary>
    /// Gets the unit's singular formal name.
    /// </summary>
    /// <value>
    /// The unit's singular formal name.
    /// </value>
    /// <seealso cref="PluralName"/>
    /// <seealso cref="Abbreviation"/>
    static abstract string SingularName { get; }

    /// <summary>
    /// Gets the unit's name in plural form.
    /// </summary>
    /// <value>
    /// The unit's name in plural form. If not available, the plural form
    /// is generated by appending an "s" to the unit's singular name.
    /// </value>
    /// <seealso cref="SingularName"/>
    /// <seealso cref="Abbreviation"/>
    static virtual string PluralName { get; } = $"{TSelf.SingularName}s";

    /// <summary>
    /// Optional. Gets the unit's abbreviation or, if not available, an empty string.
    /// </summary>
    /// <value>
    /// The unit's abbreviation or, if not available, an empty string.
    /// </value>
    /// <seealso cref="SingularName"/>
    /// <seealso cref="PluralName"/>
    static virtual string Abbreviation { get; } = string.Empty;

    /// <summary>
    /// Optional. Gets the systems of units the unit belongs to.
    /// </summary>
    /// <value>
    /// The systems of units the unit belongs to or <see cref="SystemOfUnits.None"/>
    /// if not applicable. The default value is <see cref="SystemOfUnits.None"/>.
    /// </value>
    static virtual SystemOfUnits[] SystemsOfUnits { get; } = [ SystemOfUnits.None ];

    /// <summary>
    /// Optional. Gets the description for the unit.
    /// </summary>
    /// <value>
    /// The description for the unit or an empty string if not available.
    /// </value>
    static virtual string Description => string.Empty;
}
