#pragma warning disable format

namespace ConstTypeArgs.UnitsOfMeasure;

/// <summary>
/// The <see cref="UnitOfMeasure"/> record provides information describing a unit of measure.
/// </summary>
/// <seealso cref="IUnitInfo{TSelf}"/>
public sealed record UnitOfMeasure
{
    /// <summary>
    /// Required. Gets &amp; inits the unit of measure's singular formal name.
    /// </summary>
    /// <value>
    /// The unit of measure's singular formal name.
    /// </value>
    /// <seealso cref="PluralName"/>
    /// <seealso cref="Abbreviation"/>
    public required string SingularName { get; init; }

    /// <summary>
    /// The backing field for the <see cref="PluralName"/> property.
    /// </summary>
    private string _pluralName = string.Empty;

    /// <summary>
    /// Optional. Gets &amp; inits the unit of measure's name in plural form.
    /// </summary>
    /// <value>
    /// The unit of measure's name in plural form. If not available, the plural form
    /// is generated by appending an "s" to the unit's singular name.
    /// </value>
    /// <seealso cref="SingularName"/>
    /// <seealso cref="Abbreviation"/>
    public string PluralName
    {
        get  => _pluralName;
        init => _pluralName = string.IsNullOrEmpty(value) ? $"{SingularName}s" : value;
    }

    /// <summary>
    /// Optional. Gets the unit of measure's abbreviation.
    /// </summary>
    /// <value>
    /// The unit of measure's abbreviation or, if not available, an empty string.
    /// </value>
    /// <seealso cref="SingularName"/>
    /// <seealso cref="PluralName"/>
    public string Abbreviation { get; init; } = string.Empty;

    /// <summary>
    /// Gets &amp; inits the systems of units the unit of measure belongs to.
    /// </summary>
    /// <value>
    /// The systems of units the unit of measure belongs to or <see cref="SystemOfUnits.None"/>
    /// if not applicable. The default value is <see cref="SystemOfUnits.None"/>.
    /// </value>
    public SystemOfUnits[] SystemsOfUnits { get; init; } = [ SystemOfUnits.None ];

    /// <summary>
    /// Optional. Gets &amp; inits the description for the unit of measure.
    /// </summary>
    /// <value>
    /// The description for the unit of measure. The default value is an empty string.
    /// </value>
    public string Description { get; init; } = string.Empty;

    /// <summary>
    /// Creates a new <see cref="UnitOfMeasure"/> using <typeparamref name="TUnit"/>.
    /// </summary>
    /// <typeparam name="TUnit">
    /// The type of the unit of measure. The type must implement <see cref="IUnitInfo{T}"/>.
    /// </typeparam>
    /// <returns>
    /// A new <see cref="UnitOfMeasure"/> instance representing the unit of measure
    /// created from <typeparamref name="TUnit"/>.
    /// </returns>
    public static UnitOfMeasure Create<TUnit>()
        where TUnit : IUnitInfo<TUnit>
    {
        return new()
        {
            SingularName    = TUnit.SingularName,
            PluralName      = TUnit.PluralName,
            Abbreviation    = TUnit.Abbreviation,
            SystemsOfUnits  = TUnit.SystemsOfUnits,
            Description     = TUnit.Description
        };
    }
}
