<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Company>Entry Point Software</Company>
    <Authors>Zachary Layne</Authors>
    <Title>Const Type Arguments - Delegates</Title>
    <Description>ConstTypeArgs.Delegates extends the ConstTypeArgs.Core library by enabling you to “pass” delegates as generic type parameters and accessible within static contexts. This lets you customize types in a compile-time–like fashion, effectively mimicking C++ template specialization.

This lightweight solution provides type-level delegates for cleaner, more efficient, and more expressive code, making it ideal for:

- Static Configuration: Define behavior without relying on runtime parameters.
- Type Initializer Injection: Pass values directly to static constructors.
Flexible Validation: Validate const type arguments in static constructors, field initializers, module initializers, via static analysis, etc.
- Constructors: Eliminate unnecessary instance-level initialization.
- And more.

The package provides const type arguments for basic predicates and logical operators (AND, NAND, OR, XOR, NOR, NIMPLY, IMPLY). Support is provided for Func, Action, Comparison, Converter, and Predicaate delegates, as well as new delegates:

- TResult RefFunction&lt;T, out TResult&gt;(ref T reference);
- TResult RefFunction&lt;T, in TArg, out TResult&gt;(ref T reference,
    TArg arg);
- TResult RefFunction&lt;T, in TArg1, in TArg2, out TResult&gt;(ref T reference,
    TArg1 arg1, TArg2 arg2);
- void SpanProcedure&lt;T, in TArg&gt;(Span&lt;T&gt; span, TArg arg);
- void RefProcedure&lt;T&gt;(ref T reference);
- void RefProcedure&lt;T, in TArgs&gt;(ref T reference, TArgs arguments);
- void ReadOnlySpanProcedure&lt;T, in TArg&gt;(ReadOnlySpan&lt;T&gt; span, TArg arg);

Support is also provided for arrays of all of these types as well as domain-specific types.</Description>
    <Copyright>Copyright (c) 2025 Zachary Layne</Copyright>
    <PackageReadmeFile>README.MD</PackageReadmeFile>
    <PackageIcon>Delegate.png</PackageIcon>
    <RepositoryUrl>https://github.com/zacharylayne/ConstTypeArgs</RepositoryUrl>
    <IncludeSource>true</IncludeSource>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageTags>constants; const-type-args; generics; static-abstract-interface-members; delegate</PackageTags>
    <PackageReleaseNotes>Initial release.</PackageReleaseNotes>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <DocumentationFile>ConstTypeArgs.Delegates.xml</DocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageProjectUrl>https://github.com/zacharylayne/ConstTypeArgs</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
    <IsTrimmable>True</IsTrimmable>
    <DebugType>portable</DebugType>
    <WarningLevel>8</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Deterministic>true</Deterministic>
    <IsTrimmable>True</IsTrimmable>
    <DebugType>portable</DebugType>
    <IncludeSource>true</IncludeSource>
    <EnableSourceLink>true</EnableSourceLink>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <WarningLevel>8</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\Icons\Delegate.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ConstTypeArgs.Core" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.MD">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
