<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <DocumentationFile>ConstTypeArgs.Console.xml</DocumentationFile>
    <Title>Const Type Arguments - System Console</Title>
    <Authors>Zachary Layne</Authors>
    <Company>Entry Point Software</Company>
    <Description>ConstTypeArgs.Console extends the ConstTypeArgs.Core library by enabling you to “pass” System.Console-related values as generic type parameters, accessible from within static contexts. This lets you customize types in a compile-time–like fashion, effectively mimicking C++ template specialization.

This lightweight solution provides type-level ConsoleColor, ConsoleKey, ConsoleModifiers, and ConsoleSpecialKey values for cleaner, more efficient, and more expressive code, making it ideal for:

- Static Configuration: Define behavior without relying on runtime parameters.
- Type Initializer Injection: Pass values directly to static constructors.
- Flexible Validation: Validate const type arguments in static constructors, field initializers, module initializers, via static analysis, etc.
- Constructors: Eliminate unnecessary instance-level initialization.
- And more.

The package provides const type arguments for all ConsoleColor, ConsoleKey, ConsoleModifiers, and ConsoleSpecialKey values, as well as support for arrays of those types and domain-specific types.</Description>
    <Copyright>Copyright (c) 2024 Zachary Layne</Copyright>
    <PackageIcon>Console.png</PackageIcon>
    <PackageReadmeFile>README.MD</PackageReadmeFile>
    <RepositoryUrl>https://github.com/zacharylayne/ConstTypeArgs</RepositoryUrl>
    <IncludeSource>true</IncludeSource>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageTags>constants; const-type-args; generics; static-abstract-interface-members; console</PackageTags>
    <PackageReleaseNotes>Initial release.</PackageReleaseNotes>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageProjectUrl>https://github.com/zacharylayne/ConstTypeArgs</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsTrimmable>True</IsTrimmable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Deterministic>true</Deterministic>
    <IsTrimmable>True</IsTrimmable>
    <DebugType>portable</DebugType>
    <IncludeSource>true</IncludeSource>
    <EnableSourceLink>true</EnableSourceLink>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\Icons\Console.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ConstTypeArgs.Core" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ConstTypeArgs.Delegates\ConstTypeArgs.Delegates.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.MD">
      <PackagePath>\</PackagePath>
      <Pack>True</Pack>
    </None>
  </ItemGroup>

</Project>
